
services:
  mysql:
    image: mysql:8.0.22
    container_name: kafori-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "mysql_zxtASb"
      MYSQL_DATABASE: "kafori"
      TZ: "Asia/Shanghai"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./settings/kafori.sql:/docker-entrypoint-initdb.d/1_kafori.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hmysql", "-uroot", "-pmysql_zxtASb"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: kafori-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redis_ezDtRP"]
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_ezDtRP", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: feelliao/kafori-backend:2.0dev
    container_name: kafori-backend
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    expose:
      - "10020"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      # 使用容器内专用配置，覆盖默认 settings.yaml（把主机名改成 mysql/redis）
      - ./settings/backend_settings.yaml:/app/backend/conf/settings.yaml:ro
      # 可选：持久化日志
      - ./logs:/app/backend/logs
      - ./ref:/app/ref:ro # 可选：挂载参考基因组目录


  frontend:
    image: feelliao/kafori-frontend:latest
    container_name: kafori-frontend
    depends_on:
      backend:
        condition: service_started
      sequenceserver:
        condition: service_started
    restart: unless-stopped
    ports:
      - "8091:80"
      - "8092:443"
    volumes:
      # 用挂载覆盖 Nginx 配置（或删除这两行，使用镜像内置配置）
      - ./settings/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./settings/conf.d:/etc/nginx/conf.d:ro

  sequenceserver:
    image: wurmlab/sequenceserver
    container_name: kafori-sequenceserver
    restart: unless-stopped 
    expose:
      - "4567"
    volumes:
      - /path_to_your_blastdb:/db:ro # 挂载你的 BLAST 数据库目录
      - ./settings/sequenceserver_settings.conf:/root/.sequenceserver.conf:ro

volumes:
  mysql_data:
  redis_data:
