version: '3.8'

services:
  mysql:
    image: mysql:8.0.22
    container_name: kafori-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "mysql_zxtASb"
      MYSQL_DATABASE: "kafori"
      TZ: "Asia/Shanghai"
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_0900_ai_ci
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - kafori.sql:/docker-entrypoint-initdb.d/1_kafori.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hmysql", "-uroot", "-pmysql_zxtASb"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: kafori-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redis_ezDtRP"]
    ports:
      - "6382:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_ezDtRP", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    container_name: kafori-backend
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "10020:10020"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      # 使用容器内专用配置，覆盖默认 settings.yaml（把主机名改成 mysql/redis）
      - settings.docker.yaml:/opt/kafori/backend/conf/settings.yaml:ro
      # 可选：持久化日志
      - logs/kafori_backend_running.log:/opt/kafori/backend/kafori_running.log

      - ref:/opt/kafori/ref:ro


  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: kafori-frontend
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 用挂载覆盖 Nginx 配置（或删除这两行，使用镜像内置配置）
      - frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend/conf.d:/etc/nginx/conf.d:ro

volumes:
  mysql_data:
  redis_data:
